### ISSUE TITLE
Any plan for data analysis?

### ISSUE THREAD

**Issue by ZihanWang314** [opencsapp/opencsapp.github.io#164]
Thank you for building such an open platform! As the applicants' background dps are significant for application, I believe that analyzing the weights of the features would be of great help for the next year's applicants to improve their background purposefully. Maybe simple methods such as linear regression will help. Would you like to add such a function?

**Comment by xichenpan** [comment]
@ZihanWang314 Hi, that's an interesting idea! While it seems we do not have enough datapoints to predict. I think it is a good idea to develop a plugin of ChatGPT using few-shot prediction to help people find out the possibility of getting admitted
